// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Wims.Data;

namespace Wims.Data.Migrations
{
    [DbContext(typeof(MigrationContext))]
    [Migration("20190213135507_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.2-servicing-10034")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Wims.Data.Models.AddressDb", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AddressLine1");

                    b.Property<string>("AddressLine2");

                    b.Property<string>("City");

                    b.Property<string>("PostalCode");

                    b.Property<string>("Province");

                    b.Property<DateTime>("createdDateUtc");

                    b.Property<DateTime>("modifiedDateUtc");

                    b.HasKey("Id");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("Wims.Data.Models.EventDb", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("EventType");

                    b.Property<int?>("LocationId");

                    b.Property<string>("Name");

                    b.Property<DateTime>("createdDateUtc");

                    b.Property<DateTime>("endDateTimeInUtc");

                    b.Property<DateTime>("modifiedDateUtc");

                    b.Property<DateTime>("startDateTimeInUtc");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("Wims.Data.Models.LocationDb", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AddressId");

                    b.Property<string>("Email");

                    b.Property<int>("LocationType");

                    b.Property<string>("Phone");

                    b.Property<string>("Website");

                    b.Property<DateTime>("createdDateUtc");

                    b.Property<DateTime>("modifiedDateUtc");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("Wims.Data.Models.SevadaarDb", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email");

                    b.Property<int?>("EventDbId");

                    b.Property<string>("Name");

                    b.Property<string>("Phone");

                    b.Property<string>("ProfilePicture");

                    b.Property<int>("SevaType");

                    b.Property<string>("Website");

                    b.Property<DateTime>("createdDateUtc");

                    b.Property<DateTime>("modifiedDateUtc");

                    b.HasKey("Id");

                    b.HasIndex("EventDbId");

                    b.ToTable("SevadaarDb");
                });

            modelBuilder.Entity("Wims.Data.Models.EventDb", b =>
                {
                    b.HasOne("Wims.Data.Models.LocationDb", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId");
                });

            modelBuilder.Entity("Wims.Data.Models.LocationDb", b =>
                {
                    b.HasOne("Wims.Data.Models.AddressDb", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId");
                });

            modelBuilder.Entity("Wims.Data.Models.SevadaarDb", b =>
                {
                    b.HasOne("Wims.Data.Models.EventDb")
                        .WithMany("Sevadaars")
                        .HasForeignKey("EventDbId");
                });
#pragma warning restore 612, 618
        }
    }
}
